#!/bin/bash

#########################################################################
# EXAM EVENT TRACKING SYSTEM - COMPLETE TESTING GUIDE
#########################################################################

echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                   EXAM EVENT TRACKING SYSTEM                      ║"
echo "║                                                                   ║"
echo "║       React Page + Event Logging + MySQL Database Tracking        ║"
echo "║                                                                   ║"
echo "║  Testing: Tab Switching, Page Refresh, Time per Question          ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 IMPLEMENTATION SUMMARY"
echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "✅ BACKEND (Node.js/Express)"
echo "   📁 Database:"
echo "      - Created: exam_events table"
echo "      - Columns: event_type, event_details (JSON), time_spent_seconds, timestamp"
echo "      - Indexes: submission_id, student_id, event_type"
echo ""
echo "   📍 API Endpoints:"
echo "      - POST /api/submissions/:submissionId/events"
echo "      - GET /api/submissions/:submissionId/events"
echo "      - GET /api/submissions/:submissionId/events/summary"
echo ""
echo "   📊 Event Types:"
echo "      - exam_started"
echo "      - question_viewed"
echo "      - answer_saved (with time_spent_seconds)"
echo "      - tab_switched (action: switched_away/returned)"
echo "      - page_refreshed"
echo "      - exam_submitted (includes score, % etc)"
echo ""

echo "✅ FRONTEND (React/TakeExam.jsx)"
echo "   🔍 Automatic Tracking:"
echo "      - visibilitychange listener: Detects tab switches"
echo "      - beforeunload listener: Detects page refresh"
echo "      - Timer: Measures time per question"
echo "      - Hook: Logs events on answer selection"
echo ""
echo "   🎯 Suspicious Activity Flags:"
echo "      - tabSwitches > 3 = HIGH risk"
echo "      - pageRefreshes > 2 = HIGH risk"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "🧪 TESTING PROCEDURE - 4 STEPS"
echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "STEP 1️⃣ : Automated Backend Test (5 minutes)"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "Run the automated test script:"
echo ""
echo "  cd /home/praveen/Desktop/projects/cyberproject/backend"
echo "  ./test_exam_events.sh"
echo ""
echo "This will:"
echo "  ✓ Verify backend is running"
echo "  ✓ Login as student1"
echo "  ✓ Create an exam submission"
echo "  ✓ Log 8+ different events"
echo "  ✓ Retrieve all events from database"
echo "  ✓ Generate suspicious activity summary"
echo "  ✓ Show you the MySQL query to verify"
echo ""
echo "Expected Output:"
echo "  ✅ All events logged successfully"
echo "  ✅ Event retrieval confirms database storage"
echo "  ✅ Summary shows suspicious activity detection"
echo ""

echo "STEP 2️⃣ : Manual Browser Test - Tab Switching (3 minutes)"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "1. Open: https://oes-frontend-drab.vercel.app"
echo "2. Login as student1 / student123"
echo "3. Click 'Start Exam'"
echo "4. Open DevTools (F12) → Console tab"
echo "5. Watch for messages:"
echo ""
echo "   Message when you START the exam:"
echo "     Expect: \"[✅ EVENT LOGGED] exam_started\""
echo ""
echo "   Message when you SWITCH TO ANOTHER TAB:"
echo "     Expect: \"⚠️ Student switched away from exam tab!\""
echo "             \"[✅ EVENT LOGGED] tab_switched\""
echo ""
echo "   Message when you RETURN TO EXAM TAB:"
echo "     Expect: \"✅ Student returned to exam tab\""
echo "             \"[✅ EVENT LOGGED] tab_switched\""
echo ""
echo "✅ SUCCESS: See these 3 messages in console"
echo ""

echo "STEP 3️⃣ : Manual Browser Test - Page Refresh (2 minutes)"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "1. While exam is running, select any answer"
echo "2. Open Console (F12)"
echo "   Expect: \"[✅ EVENT LOGGED] answer_saved\""
echo ""
echo "3. Press F5 to REFRESH the page"
echo "   Expect: \"[✅ EVENT LOGGED] page_refreshed\""
echo ""
echo "4. Exam page reloads with your answer STILL SAVED"
echo ""
echo "✅ SUCCESS: Answer survived refresh (stored in DB)"
echo ""

echo "STEP 4️⃣ : Verify Data in MySQL Database (5 minutes)"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "Connect to cPanel MySQL:"
echo ""
echo "  mysql -h localhost -u freshmil_oesuser -p'Reddys4512@' freshmil_oes"
echo ""
echo "Run these queries:"
echo ""
echo "🔍 View Recent Submissions:"
echo "  SELECT submission_id, student_id, submitted_at"
echo "  FROM submissions"
echo "  ORDER BY submitted_at DESC LIMIT 5\\G"
echo ""
echo "🔍 View All Events for a Submission (use submission_id from above):"
echo "  SELECT * FROM exam_events"
echo "  WHERE submission_id = 5"
echo "  ORDER BY timestamp ASC\\G"
echo ""
echo "🔍 Get Event Summary:"
echo "  SELECT event_type, COUNT(*) as count, MAX(timestamp) as last"
echo "  FROM exam_events"
echo "  WHERE submission_id = 5"
echo "  GROUP BY event_type\\G"
echo ""
echo "🔍 Find Suspicious Activity (multiple tab switches):"
echo "  SELECT submission_id,"
echo "         COUNT(*) as suspicious_events,"
echo "         GROUP_CONCAT(event_type) as events"
echo "  FROM exam_events"
echo "  WHERE event_type = 'tab_switched'"
echo "  GROUP BY submission_id"
echo "  HAVING suspicious_events > 2\\G"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "📊 EXPECTED RESULTS AT EACH STAGE"
echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "After Step 1 (Automated Test):"
echo "  ✅ 11+ events in database"
echo "  ✅ Events include: started, tab_switches (3), refreshes (2), answers"
echo "  ✅ Suspicious Activity Level = HIGH (due to test data)"
echo ""

echo "After Step 2 (Tab Switching):"
echo "  ✅ 3 tab_switched events logged"
echo "  ✅ Each has timestamp and action (switched_away/returned)"
echo "  ✅ Console shows real-time detection"
echo ""

echo "After Step 3 (Page Refresh):"
echo "  ✅ 1 page_refreshed event logged"
echo "  ✅ Answer data persisted to database"
echo "  ✅ Session maintained across refresh"
echo ""

echo "After Step 4 (Database Verification):"
echo "  ✅ exam_events table has rows"
echo "  ✅ Each event has: type, timestamp, details (JSON)"
echo "  ✅ Foreign keys link to submissions and users"
echo "  ✅ Summary shows event counts and suspicious activity"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "🎯 KEY FILES TO UNDERSTAND"
echo "───────────────────────────────────────────────────────────────────"
echo ""

echo "Backend:"
echo "  📄 src/migrations/001_create_exam_events_table.js"
echo "     → Creates the database table with proper schema"
echo ""
echo "  📄 src/routes/exam-events.js"
echo "     → API endpoints for logging and retrieving events"
echo "     → Suspicious activity detection logic"
echo ""
echo "  📄 test_exam_events.sh"
echo "     → Full integration test (run this first!)"
echo ""

echo "Frontend:"
echo "  📄 src/pages/TakeExam.jsx"
echo "     → Automatic event tracking"
echo "     → visibilitychange listener (tab switching)"
echo "     → beforeunload listener (page refresh)"
echo "     → Time tracking per question"
echo ""

echo "Documentation:"
echo "  📄 EXAM_EVENTS_DOCUMENTATION.md"
echo "     → Full API reference"
echo "     → Database schema details"
echo "     → Advanced use cases"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "❓ TROUBLESHOOTING"
echo "───────────────────────────────────────────────────────────────────"
echo ""

echo "Q: Events not showing in console?"
echo "A: Make sure you have DevTools open BEFORE starting the exam"
echo ""

echo "Q: Getting 'exam_events table doesn't exist'?"
echo "A: Migration must run when backend starts. Check server logs:"
echo "   tail -f /var/log/nodejs.log | grep exam_events"
echo ""

echo "Q: Can't connect to MySQL from command line?"
echo "A: Verify credentials are correct, database exists:"
echo "   mysql -h localhost -u freshmil_oesuser -p'Reddys4512@' -e 'SELECT 1'"
echo ""

echo "Q: Tab switching events not logging?"
echo "A: Some browsers restrict visibilitychange. Try:"
echo "   - Chrome/Edge: Works perfectly"
echo "   - Firefox: Supported"
echo "   - Safari: May have permissions issue"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "✨ DEPLOYMENT STATUS"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "✅ Code committed to GitHub:"
echo "   - Backend: commit e8f86f4 (exam event tracking)"
echo "   - Frontend: commit e448736 (TakeExam tracking)"
echo ""
echo "⏳ Frontend deployment to Vercel:"
echo "   - Automatically deploying from main branch"
echo "   - Check https://github.com/praveenreddy4512/oes-frontend/deployments"
echo ""
echo "⏳ Backend deployment to cPanel:"
echo "   - Pull latest code on cPanel: git pull origin main"
echo "   - Restart Node.js: pkill -f 'node src/server.js' && node src/server.js &"
echo "   - Migration runs automatically on startup"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""

echo "🚀 NEXT STEPS"
echo "───────────────────────────────────────────────────────────────────"
echo ""
echo "1. Run automated test: ./test_exam_events.sh"
echo "2. Test manually in browser (tab switching)"
echo "3. Verify data in MySQL database"
echo "4. Check DevTools console for event logs"
echo "5. Review EXAM_EVENTS_DOCUMENTATION.md for advanced features"
echo ""

echo "═════════════════════════════════════════════════════════════════════"
echo ""
