#!/bin/bash

echo "================================================"
echo "QUICK RESTART INSTRUCTIONS FOR cPANEL"
echo "================================================"
echo ""
echo "📌 METHOD 1: SSH (Fastest)"
echo "Run these commands:"
echo ""
echo "ssh your-cpanel-username@oes.freshmilkstraightfromsource.com"
echo "cd /home/freshmil_oesuser/public_html/oes-backend"  
echo "git pull origin main"
echo "pkill node"
echo "sleep 2"
echo "npm start"
echo ""
echo "Wait for: 'Server running on port 5000' message"
echo ""
echo "================================================"
echo "📌 METHOD 2: cPanel GUI (Easiest if you're not comfortable with SSH)"
echo ""
echo "1. Log in to cPanel: https://oes.freshmilkstraightfromsource.com:2087"
echo "2. Find 'Node.js App Manager' or 'Node.js Selector'"
echo "3. Click the oes-backend app"
echo "4. Click 'STOP' (wait for it to say Stopped)"
echo "5. Click 'START' (wait for it to say Running)"
echo "6. Wait 30 seconds for it to fully start"
echo ""
echo "================================================"
echo ""
echo "After restarting, test by:"
echo "1. Go to https://oes.frontend-drab.vercel.app"
echo "2. Login as admin"
echo "3. Go to Users → Create Student"
echo "4. Type a username like 'testuser_1234'"
echo "5. Type password 'Test@1234'"
echo "6. Type email 'test@test.com'"
echo "7. Select Role: 'student'"
echo "8. ☑️  SELECT AT LEAST ONE GROUP!"
echo "9. Click Create"
echo "10. Open DevTools with F12"
echo "11. Go to Console tab"
echo "12. Look for messages with [✅] or [ERROR]"
echo ""
echo "================================================"
echo ""
